import turtle
turtle.setup(800,600)
turtle.color("blue","red")
turtle.speed(9)
turtle.fillcolor("red")
turtle.goto(0, -200)
turtle.begin_fill()
turtle.circle(200)
turtle.end_fill()
turtle.penup()
turtle.goto(0, -170)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.circle(170)
turtle.end_fill()
turtle.penup()
turtle.goto(0, -130)
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.circle(130)
turtle.end_fill()
turtle.penup()
turtle.goto(0, -100)
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(0, 100)
turtle.fillcolor("white")
turtle.begin_fill()
turtle.right(72)
for i in range(5):
	turtle.fd(185)
	turtle.right(144)
turtle.end_fill()
input()
