import turtle
turtle.setup(800,600)
turtle.pensize(5)
turtle.color("yellow","red")
turtle.penup()
#turtle.setheading(-90)
#turtle.fd(45)
#turtle.setheading(-180)
turtle.backward(90)
turtle.pendown()
turtle.circle(100)
input()